language: node_js
dist: focal
jobs:
  include:
    - name: "JavaScript driver"
      node_js: "10"
      services:
        - postgresql
      addons:
        postgresql: "12"
      script:
        - psql --version
        - pg_isready
        - psql -c "CREATE DATABASE postgres;" -U postgres
        - rm -fr ./node_modules
        - hash -r
        - npm install
        - node travis-test.js
notifications:
  email: false
sudo: false
